<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyContent</RootNamespace>
    <AssemblyName>MyContent</AssemblyName>
    <Version>0.1.2</Version>
    <AssemblyVersion>0.1.2.0</AssemblyVersion>
    <FileVersion>0.1.2.0</FileVersion>
    <InformationalVersion>0.1.2</InformationalVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
    <PackageReference Include="Supabase" Version="8.1.0" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Legal\*.txt" />
  </ItemGroup>
</Project>
